version: '3'
services:
  tesla-player:
    build : .
    environment:
      - APP_BASE_URL=http://localhost:5000 # <-- The URL must be the external URL of the application (as seen in the browser)
    volumes:
      - ./uploads:/python-docker/uploads
    ports:
      - "5000:5000"
    restart: unless-stopped
