CREATE TABLE IF NOT EXISTS Playlist (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT
);

CREATE TABLE IF NOT EXISTS PlaylistSong(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	idx INTEGER,
	playlist_id INTEGER,
	song_id INTEGER,
	FOREIGN KEY(playlist_id) REFERENCES Playlist(id) ON DELETE CASCADE,
	FOREIGN KEY(song_id) REFERENCES Song(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Song (
	id 				INTEGER PRIMARY KEY AUTOINCREMENT,
	midiFile_id 	INTEGER,
	name 			TEXT,
	output_mapping_1 INTEGER,
	output_mapping_2 INTEGER,
	FOREIGN KEY (midiFile_id) REFERENCES MidiFile(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS MidiFile (
	id 				INTEGER PRIMARY KEY AUTOINCREMENT,
	name 			TEXT,
	path 			TEXT
);

CREATE TABLE IF NOT EXISTS SysexCommand (
	id 				INTEGER PRIMARY KEY AUTOINCREMENT,
	song_id 		INTEGER,
	command 		TEXT,
	value 			TEXT,
	indexInSong		INTEGER,
	FOREIGN KEY (song_id) REFERENCES Song(id) ON DELETE CASCADE
);
